"""empty message

Revision ID: 88c62281eeda
Revises: 8c5721f94954
Create Date: 2024-11-18 00:38:29.774127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c62281eeda'
down_revision = '8c5721f94954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.String(length=12),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
